#!/usr/bin/env bash
# Bash script that uses a loop to display various strings

i=1
while [[ $i -le 20 ]]; do
	echo $i
	if (( i  == 4 )); then
		echo "bad luck from China"
	elif (( i == 9 )); then
		echo "bad luck from Japan"
	elif [ "$i" -eq 17 ]; then
		echo "bad luck from Italy"
	fi
	i=$((i + 1))
done
